---
version: "3"

services:
  # db_postgres:
  #   image: postgres:14.2
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: bkms
  #     POSTGRES_PASSWORD: bkmspostgres
  #     POSTGRES_DB: dblp
  #   expose:
  #     - "5432"
  #   volumes:
  #     - db-data-postgres:/var/lib/postgresql/data
  #   networks:
  #     - backend

  db_neo4j:
    image: neo4j:4.4.6-community
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/bkmsneo4j
      NEO4J_dbms_memory_pagecache_size: 8G
      NEO4J_dbms_memory_heap_max__size: 8G
      NEO4J_dbms_default__listen__address: 0.0.0.0
      NEO4JLABS_PLUGINS: '["apoc", "graph-data-science"]'
    ports:
      - "54010:7687"
    volumes:
      - db-data-neo4j:/data
      - db-logs-neo4j:/logs
    networks:
      - backend

  # frontend:
  #   restart: always
  #   ports:
  #     - "54015:8080"
  #   depends_on:
  #     - db_postgres
  #     - db_neo4j
  #   networks:
  #     - backend
  #     - frontend
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   entrypoint: "jupyter lab --allow-root --config=config/jupyter_lab_config.py /code"

networks:
  backend:
    driver: bridge
  # frontend:
  #   driver: bridge

volumes:
  db-data-postgres:
  db-data-neo4j:
  db-logs-neo4j:

