[tool.poetry]
name = "bkms2022_project"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.1.2"
neo4j = "^4.4.3"
psycopg2-binary = "^2.9.3"
jupyterlab = "^3.4.1"


[tool.poetry.dev-dependencies]
black = "^22.3.0"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
